
name: copilot_ephys
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - "numpy<2"
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - h5py
  - pytest
  - jupyter
