[metadata]
name = visdetect
version = 0.0.0
description = visdetect analysis package

[options]
packages = find:
package_dir =
    = src
install_requires =
    numpy
    scipy
    pandas
    matplotlib
    seaborn
    tqdm
    pyyaml
    scikit-learn

[tool:pytest]
norecursedirs = cleanup_archive
testpaths = tests
