"""
Analyze neural activity during FA trials, stratified by lick count (Single vs Multi).

Logic:
1. Identify Lick-Excited units using existing `lick_responsiveness.csv` (generated by pipeline).
2. For each session:
   - Identify FA trials.
   - Count licks in [0, 1.5]s window post-first-lick to classify "Single" (1) vs "Multi" (>1).
   - Compute PETH for Excited units for both conditions.
   - Average across units to get Session Population Trace.
3. Visualize:
   - Heatmaps of Population Activity (Single vs Multi).
   - Example Session Traces.
"""

import argparse
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from datetime import datetime
from tqdm import tqdm
from scipy.ndimage import gaussian_filter1d
import sys


from visdetect.core.session import load_session
from visdetect.analysis.behavior import get_trial_dataframe
from visdetect.analysis.config import load_staging_manifest

def parse_date(session_name):
    try:
        date_str = session_name.split('_')[-1]
        return datetime.strptime(date_str, "%d%m%Y")
    except:
        return datetime.min

def get_event_times(ni_events, key_candidates):
    """Robustly retrieve event times from ni_events dict."""
    if not ni_events:
        return np.array([])
    
    found_times = []
    for key in key_candidates:
        if key in ni_events:
            val = ni_events[key]
            # Handle dict with 'rise_t' or direct array
            if isinstance(val, dict) and 'rise_t' in val:
                found_times.append(np.array(val['rise_t']).flatten())
            else:
                found_times.append(np.array(val).flatten())
            
    if found_times:
        return np.concatenate(found_times)
    return np.array([])

def compute_psth(spikes, triggers, window, bin_size):
    """Compute simple PSTH."""
    t_min, t_max = window
    bins = np.arange(t_min, t_max + bin_size, bin_size)
    centers = bins[:-1] + bin_size / 2
    
    all_rel = []
    triggers = np.sort(triggers)
    spikes = np.sort(spikes)
    
    for t in triggers:
        if np.isnan(t): continue
        # Slice spikes
        idx_start = np.searchsorted(spikes, t + t_min)
        idx_end = np.searchsorted(spikes, t + t_max)
        relevant = spikes[idx_start:idx_end]
        all_rel.extend(relevant - t)
        
    counts, _ = np.histogram(all_rel, bins=bins)
    if len(triggers) > 0:
        rate = counts / (len(triggers) * bin_size)
    else:
        rate = np.zeros_like(centers)
        
    return centers, rate

def get_responsive_units(session_stats_dir):
    """Load lick_responsiveness.csv and return dict with excited and inhibited cluster IDs."""
    csv_path = session_stats_dir / "lick_responsiveness.csv"
    if not csv_path.exists():
        return None
    
    try:
        df = pd.read_csv(csv_path)
        # Criteria: Significant AND Positive Delta (Excited) vs Negative (Inhibited)
        excited = df[(df['is_significant'] == True) & (df['delta_mean'] > 0)]
        inhibited = df[(df['is_significant'] == True) & (df['delta_mean'] < 0)]
        return {
            'excited': excited['cluster_id'].values,
            'inhibited': inhibited['cluster_id'].values
        }
    except Exception as e:
        print(f"Error reading stats {csv_path}: {e}")
        return None

def process_session(pkl_path, stats_root, session_name):
    # 1. Check for Responsive Units first
    # Structure of stats_root: FIGURES/lick/BG_046/23062025/lick_responsiveness.csv
    # We need to match session_name (e.g., 23062025)
    
    # Try direct match
    s_folder = stats_root / session_name
    if not s_folder.exists():
        # Try finding partial match
        # Assuming session_name in manifest is '23062025' or 'BG_046_23062025'
        # The folders in FIGURES/lick/BG_046/ seems to be 'DDMMYYYY'
        # Let's try to extract date part
        date_part = session_name.split('_')[-1]
        s_folder = stats_root / date_part
        
    if not s_folder.exists():
        # print(f"No stats folder found for {session_name} at {s_folder}")
        return None
        
    units_by_type = get_responsive_units(s_folder)
    if units_by_type is None:
        return None
        
    # 2. Load Pickle
    try:
        session = load_session(pkl_path)
    except Exception:
        return None
        
    # 3. Get Behavior & Lick Times
    df = get_trial_dataframe(session)
    lick_keys = ['Lick_L', 'lick_L']
    all_licks = get_event_times(session.ni_events, lick_keys)
    if len(all_licks) > 0:
        all_licks = np.sort(np.unique(all_licks))
    else:
        return None
        
    start_keys = ['Baseline_ON', 'trial_start_times']
    trial_starts = get_event_times(session.ni_events, start_keys)
    if len(trial_starts) == 0:
        return None
        
    # 4. Stratify FA Trials
    fa_trials = df[df['is_fa']]
    
    if fa_trials.empty:
        return None
        
    single_lick_aligns = []
    multi_lick_aligns = []
    
    # Lick Counting Window (post-first-lick)
    count_window = 1.0 # seconds
    
    for _, row in fa_trials.iterrows():
        idx = int(row['trial_idx'])
        if idx >= len(trial_starts): continue
        
        rt = row['rt']
        if np.isnan(rt): continue
        
        t_align = trial_starts[idx] + rt
        
        # Count licks in [t_align, t_align + count_window]
        # Include the trigger lick at t=0 (so should be >= 1)
        # Using a small negative epsilon for start to ensure trigger lick is counted
        # Actually, let's look at licks > t_align (subsequent licks)
        # If any lick exists in (t_align, t_align + 1.0], it's Multi.
        
        # Using searchsorted
        # t_align is float, maybe not exact match in all_licks due to precision
        # let's look at window [t_align + 0.05, t_align + 1.5]
        # 50ms buffer to skip the trigger lick
        
        l_start = np.searchsorted(all_licks, t_align + 0.05)
        l_end = np.searchsorted(all_licks, t_align + 1.0)
        
        count = l_end - l_start
        # If count > 0, it means there are MORE licks after the trigger -> Multi
        
        if count == 0:
            single_lick_aligns.append(t_align)
        else:
            multi_lick_aligns.append(t_align)
            
    # 5. Compute Neural Activity
    # Window [-1, 2]
    window = [-1.0, 2.0]
    bin_size = 0.05 # 50ms
    sigma = 1.0 # Smoothing sigma (in bins). 1.0 * 50ms = 50ms
    
    session_results = {
        'session_name': session_name,
        'n_single': len(single_lick_aligns),
        'n_multi': len(multi_lick_aligns)
    }

    # Inner function to compute pop trace
    def compute_trace_stats(triggers, spike_list):
        if not triggers or not spike_list:
            return None, None, None
        
        unit_traces = []
        time_axis = None
        
        for spk in spike_list:
            t, rate = compute_psth(spk, triggers, window, bin_size)
            rate_smooth = gaussian_filter1d(rate, sigma=sigma)
            
            base_idx = int(( -0.5 - window[0] ) / bin_size)
            baseline_segment = rate_smooth[:base_idx]
            
            if len(baseline_segment) > 0:
                mu = np.mean(baseline_segment)
                std = np.std(baseline_segment)
                if std > 0.1: 
                    z = (rate_smooth - mu) / std
                    unit_traces.append(z)
                    
            if time_axis is None:
                time_axis = t
                
        if not unit_traces:
            return None, None, None
        
        arr = np.array(unit_traces)
        mean_trace = np.nanmean(arr, axis=0)
        sem_trace = np.nanstd(arr, axis=0, ddof=1) / np.sqrt(arr.shape[0])
            
        return time_axis, mean_trace, sem_trace

    any_data = False
    
    for modulation_type in ['excited', 'inhibited']:
        cluster_ids = units_by_type[modulation_type]
        spikes = []
        for cl in session.clusters:
            if cl.cluster_id in cluster_ids:
                spikes.append(np.array(cl.spike_times))
        
        if not spikes:
            session_results[modulation_type] = None
            continue
            
        t_single, m_single, e_single = compute_trace_stats(single_lick_aligns, spikes)
        t_multi, m_multi, e_multi = compute_trace_stats(multi_lick_aligns, spikes)
        
        if t_single is None and t_multi is None:
            session_results[modulation_type] = None
            continue
            
        # Ensure common time axis if one missing
        time_axis = t_single if t_single is not None else t_multi
        
        # Pad if missing
        if m_single is None: 
            m_single = np.full_like(time_axis, np.nan)
            e_single = np.full_like(time_axis, np.nan)
        if m_multi is None: 
            m_multi = np.full_like(time_axis, np.nan)
            e_multi = np.full_like(time_axis, np.nan)
            
        session_results[modulation_type] = {
            'time': time_axis,
            'single_mean': m_single,
            'single_sem': e_single,
            'multi_mean': m_multi,
            'multi_sem': e_multi,
            'n_units': len(spikes)
        }
        any_data = True
        
    if not any_data:
        return None
        
    return session_results

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--manifest', default=None,
                        help='Path to manifest CSV (default: canonical)')
    parser.add_argument('--out', required=True)
    parser.add_argument('--stats-root', required=True, help="Root folder where lick_responsiveness.csv are stored (e.g., FIGURES/lick/BG_046)")
    parser.add_argument('--pkl-dir', required=False)
    parser.add_argument('--no-filter', action='store_true', help='Bypass SESSION_FILTER')
    args = parser.parse_args()
    
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    
    manifest = load_staging_manifest(manifest_path=args.manifest,
                                     apply_filter=not args.no_filter)
    # Restore zeros
    manifest['session_name'] = manifest['session_name'].apply(lambda x: x.zfill(8) if x.isdigit() and len(x)==7 else x)
    subject = manifest.iloc[0]['subject']
    
    manifest['parsed_date'] = manifest['session_name'].apply(lambda x: parse_date(f"{subject}_{x}"))
    manifest = manifest.sort_values('parsed_date').reset_index(drop=True)
    
    results = []
    
    print(f"Processing {len(manifest)} sessions...")
    
    for _, row in tqdm(manifest.iterrows(), total=len(manifest)):
        session_name = row['session_name']
        
        # Resolve Pickle
        if args.pkl_dir:
            cands = list(Path(args.pkl_dir).glob(f"*{session_name}*.pkl"))
            pkl_path = cands[0] if cands else None
        else:
            if 'pkl_path' in row and pd.notna(row['pkl_path']):
                pkl_path = Path(row['pkl_path'])
            else:
                pkl_path = None
                
        if not pkl_path or not pkl_path.exists():
            continue
            
        res = process_session(pkl_path, Path(args.stats_root), session_name)
        if res:
            results.append(res)
            
    if not results:
        print("No valid results found.")
        return
        
    # --- Visualization ---
    
    # Generate plots for both Excited and Inhibited
    for mod_type in ['excited', 'inhibited']:
        # Filter results that have data for this mod_type
        mod_results = [r for r in results if r[mod_type] is not None]
        
        if not mod_results:
            continue
            
        # 1. Heatmaps
        # Collect matrices
        sessions = [r['session_name'] for r in mod_results]
        mat_single = np.array([r[mod_type]['single_mean'] for r in mod_results])
        mat_multi = np.array([r[mod_type]['multi_mean'] for r in mod_results])
        time_axis = mod_results[0][mod_type]['time']
        
        fig, axes = plt.subplots(1, 2, figsize=(12, 8), sharey=True)
        
        # Color Scale - Invert for inhibited to make "activation" (inhibition) distinct?
        # Or just let viridis handle negative values naturally.
        # Let's use 'coolwarm' for bidirectional or 'viridis' for absolute.
        # Since Z-scores, 'coolwarm' centered at 0 or robust range is good.
        
        all_vals = np.concatenate([mat_single.flatten(), mat_multi.flatten()])
        all_vals = all_vals[~np.isnan(all_vals)]
        if len(all_vals) > 0:
            vmin, vmax = np.percentile(all_vals, [1, 99])
        else:
            vmin, vmax = -1, 1

        sns.heatmap(mat_single, ax=axes[0], cmap='viridis', vmin=vmin, vmax=vmax, cbar=False)
        im = sns.heatmap(mat_multi, ax=axes[1], cmap='viridis', vmin=vmin, vmax=vmax)
        
        label_text = "Excited" if mod_type == 'excited' else "Inhibited"
        axes[0].set_title(f'Single Lick FAs ({label_text})\n(Mean Z-Score)')
        axes[1].set_title(f'Multi Lick FAs ({label_text})\n(Mean Z-Score)')
        
        # Formatting
        n_bins = len(time_axis)
        x_indices = np.linspace(0, n_bins-1, 5)
        x_labels = np.linspace(time_axis[0], time_axis[-1], 5)
        
        for ax in axes:
            ax.set_xticks(x_indices)
            ax.set_xticklabels([f"{x:.1f}" for x in x_labels])
            ax.set_xlabel('Time (s)')
            zero_idx = np.searchsorted(time_axis, 0)
            ax.axvline(zero_idx, color='white', linestyle='--')
            
        y_indices = np.arange(len(sessions))
        axes[0].set_yticks(y_indices + 0.5)
        axes[0].set_yticklabels(sessions, fontsize=8)
        axes[0].set_ylabel('Session')
        
        plt.tight_layout()
        plt.savefig(out_dir / f"fa_neural_strat_heatmap_{mod_type}.png", dpi=300)
        plt.close()
        
        # 2. Example Traces
        n_res = len(mod_results)
        indices = [0, n_res // 2, n_res - 1]
        
        fig, axes = plt.subplots(1, 3, figsize=(15, 5), sharey=True) # allow different y-scales
        
        for ax, idx in zip(axes, indices):
            if idx >= n_res: continue
            res = mod_results[idx]
            d = res[mod_type]
            
            # Single
            ax.plot(d['time'], d['single_mean'], label=f"Single (n={res['n_single']})", color='dodgerblue')
            ax.fill_between(d['time'], d['single_mean'] - d['single_sem'], d['single_mean'] + d['single_sem'], color='dodgerblue', alpha=0.2)
            
            # Multi
            ax.plot(d['time'], d['multi_mean'], label=f"Multi (n={res['n_multi']})", color='firebrick')
            ax.fill_between(d['time'], d['multi_mean'] - d['multi_sem'], d['multi_mean'] + d['multi_sem'], color='firebrick', alpha=0.2)
            
            ax.set_title(f"{res['session_name']}\n({label_text} Units: {d['n_units']})")
            ax.set_xlabel('Time (s)')
            if idx == 0: ax.legend()
            ax.axvline(0, color='k', linestyle='--', alpha=0.5)
            ax.grid(True, alpha=0.3)
            
        axes[0].set_ylabel('Mean Z-Scored Rate')
        plt.tight_layout()
        plt.savefig(out_dir / f"fa_neural_strat_examples_{mod_type}.png", dpi=300)
        plt.close()
    
    print(f"Done. Saved to {out_dir}")

if __name__ == "__main__":
    main()
