"""Phase 6 guardrail: enforce the in-place architecture refactor.

Run from the repo root::

    py scripts/qc/check_refactor_guardrails.py

Exit code 0 if no hard violations, 1 otherwise. Designed to be wired into
``.pre-commit-config.yaml``, a git pre-commit hook, or CI — and to be
invoked by Claude's existing ``pre-commit-checker`` skill.

Enforced (HARD — exit 1 on any hit):

* No new ``sys.path.insert(...)`` in maintained code. Exempt: ``archive/``,
  ``_DeepUnitMatch_repo/``, ``AI_exploration/`` (pending triage), the
  one-off migration tools (``_migrate_imports.py``, ``_check_imports.py``),
  and any line referencing the vendored DeepUnitMatch path (``DUM`` /
  ``DeepUnitMatch`` / ``unitmatch``).
* No flat ``from (config|loader|plotting|utils) import …`` /
  ``import (config|loader|plotting|utils)``. Suite infra lives in
  ``visdetect.suite.*``; utils in ``visdetect.analysis.utils``.

Reported only (INFO — not blocking, surfaced for Phase 5 work):

* Hardcoded ``"BG_046"`` string literals (should come from
  ``visdetect.analysis.config.SUBJECT`` / ``VISDETECT_SUBJECT`` env var).
* Hardcoded ``X:/…`` data-root paths (should come from a config / env var).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SKIP_DIRS = {
    # the maintained refactor target = analysis_suite/, scripts/, tests/, src/
    "archive", "_DeepUnitMatch_repo", "AI_exploration",
    "__pycache__", ".venv", ".git", "refactor_baseline",
    "data",  # autogenerated Kilosort params, data caches — gitignored
    "notebooks",
}
SKIP_FILES = {
    # one-off refactor tools at repo root (gitignored via /_*.py)
    "_migrate_imports.py", "_check_imports.py",
    "_fix_post_error_hardcoding.py",
    "check_refactor_guardrails.py",  # self-exempt — docstring mentions sys.path.insert
    # untracked in-progress tracking pipeline work — user will clean on commit
    "run_deepunitmatch_all.py",
    "validate_long_tracks.py",
}

SYSPATH    = re.compile(r"sys\.path\.insert")
SYSPATH_OK = re.compile(r"DUM|DeepUnitMatch|unitmatch", re.I)
FLAT_IMPORT = re.compile(
    r"^\s*(from\s+(config|loader|plotting|utils)\s+import|"
    r"import\s+(config|loader|plotting|utils)\b)"
)
BG_HARDCODE = re.compile(r"""["']BG_046["']""")
XDRIVE      = re.compile(r"""["'](X:[/\\])""")


def is_skipped(rel: Path) -> bool:
    if rel.name in SKIP_FILES:
        return True
    return any(part in SKIP_DIRS for part in rel.parts)


def main() -> int:
    hard: list[str] = []
    info: list[str] = []
    for py in sorted(REPO.rglob("*.py")):
        rel = py.relative_to(REPO)
        if is_skipped(rel):
            continue
        try:
            text = py.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for i, line in enumerate(text.splitlines(), 1):
            if SYSPATH.search(line) and not SYSPATH_OK.search(line):
                hard.append(f"{rel}:{i}: sys.path.insert — {line.strip()}")
            if FLAT_IMPORT.match(line):
                hard.append(f"{rel}:{i}: flat suite import — {line.strip()}")
            if BG_HARDCODE.search(line):
                info.append(f"{rel}:{i}: hardcoded 'BG_046' — {line.strip()}")
            if XDRIVE.search(line):
                info.append(f"{rel}:{i}: hardcoded X: path — {line.strip()}")

    if hard:
        print(f"HARD violations ({len(hard)}) — Phase 3 architecture regression:")
        for v in hard:
            print(f"  {v}")
        print()

    if info:
        print(f"INFO ({len(info)}) — Phase 5 config-hardcoding targets:")
        for v in info[:25]:
            print(f"  {v}")
        if len(info) > 25:
            print(f"  ... and {len(info) - 25} more")
        print()

    if not hard:
        print("Guardrails: PASS (Phase 3 architecture preserved)")
    else:
        print("Guardrails: FAIL -- fix the HARD violations above.")
    return 1 if hard else 0


if __name__ == "__main__":
    sys.exit(main())
